<?php
    use DynamicalWeb\WebSession;
?>
<!-- Response Tab -->
<div id="tab-response" class="dw-tab-content">
    <?php if (WebSession::get('dw_response_sections_html')): ?>
        <table class="dw-content-table">
            <?= WebSession::get('dw_response_sections_html') ?>
        </table>
    <?php else: ?>
        <div class="dw-empty-tab">No response details available.</div>
    <?php endif; ?>
</div>
