<?php 
    use DynamicalWeb\WebSession; 
?>
<!-- Server Tab -->
<div id="tab-server" class="dw-tab-content">
    <?php if (WebSession::get('dw_server_sections_html')): ?>
        <table class="dw-content-table">
            <?= WebSession::get('dw_server_sections_html') ?>
        </table>
    <?php else: ?>
        <div class="dw-empty-tab">No server information available.</div>
    <?php endif; ?>
</div>
