<?php
    use DynamicalWeb\WebSession;
?>
<!-- Session Tab -->
<div id="tab-session" class="dw-tab-content">
    <?php if (WebSession::get('dw_session_sections_html')): ?>
        <table class="dw-content-table">
            <?= WebSession::get('dw_session_sections_html') ?>
        </table>
    <?php else: ?>
        <div class="dw-empty-tab">No session information available.</div>
    <?php endif; ?>
</div>
